### ISSUE TITLE
Detonationems.com ordering

### ISSUE THREAD

**Issue by Scotty10-4** [DetonationEMS/DetonationEMS#1]
Hi, I ordered from your website. There is no way to contact you to change order? I replied to the conformation but it's squarespace? Order 10579 I don't need vr conditioner and need stepper module.. I would have not ordered if I realized the lack of support or way to contact you. What is your return policy? Can I send the vr conditioner back? I msg days ago and then just got a ship conformation. Other speeduino sites I emailed them questions and got a response next day.. A little frustrated..

**Comment by DetonationEMS** [comment]
We spoke through the proper email prior to your order. I never received any emails after than until I noticed you messaged me through my personal email that isn't monitored often, The original email we spoke through is the correct means to contact me for business matters. It can also be found at the bottom of the support page on my website. (aaron@detonationems.com)

https://www.detonationems.com/support

I am sorry for your frustration. I'll be emailing you from the correct email so we can find a resolution..
